version: "3.1"
services:
    db:
        image: mysql
        ports: 
            - "${DB_PORT}:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
        volumes:
            - ./dataBase_crud:/docker-entrypoint-initdb.d 
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - "${APP_PORT}:80"
        volumes:
            - /home/ansibleadmin/unitTest:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - ${MYSQL_PORT}:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
volumes:
    persistent:
